
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lenov
 */
public class aplikasiBukuAlamat extends javax.swing.JFrame {
    
    // Model untuk menampung data daftar kontak (Nama | Alamat | Telepon)
    private DefaultListModel<String> model;


    /**
     * Constructor utama untuk inisialisasi JFrame dan komponen aplikasi.
     */
    public aplikasiBukuAlamat() {
        initComponents(); // Membuat semua komponen GUI
        
        // Membuat model list dan memasangnya ke JList
        model = new DefaultListModel<>();
        listKontak.setModel(model);
        
         // WARNA TEMA APLIKASI
        Color green = new Color(46, 204, 113);
        Color blue  = new Color(52, 152, 219);
        Color red   = new Color(231, 76, 60);
        Color gray  = new Color(149, 165, 166);

        // STYLE UNTUK SEMUA BUTTON
        styleButton(btnTambah, green);
        styleButton(btnUbah, blue);
        styleButton(btnHapus, red);
        styleButton(btnClear, gray);

        styleButton(btnCari, blue);
        styleButton(btnReset, gray);

        styleButton(btnSort, blue);
        styleButton(btnExportCSV, green);
        styleButton(btnHapusSemua, red);
        styleButton(btnKeluar, gray);


    }
    
    /**
     * Fungsi untuk memberikan style modern ke button.
     * Mengatur warna, font, border, dan tampilan tombol.
     */
    private void styleButton(JButton btn, Color bgColor) {
        btn.setBackground(bgColor);
        btn.setForeground(Color.WHITE);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btn.setFocusPainted(false);
        btn.setContentAreaFilled(false);
        btn.setOpaque(true);
        btn.setBorderPainted(false);
    }
    
    /**
     * Validasi nomor telepon.
     * Hanya menerima angka 10–13 digit.
     */
    private boolean isValidPhone(String phone) {
        return phone.matches("\\d{10,13}");
    }   
    
    /**
     * Menghapus seluruh input pada form.
     * Digunakan setelah tambah, ubah, atau clear.
     */
    private void clearInput() {
        txtNama.setText("");
        txtAlamat.setText("");
        txtTelepon.setText("");
        txtNama.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        panelInput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtTelepon = new javax.swing.JTextField();
        panelTombol = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        panelCari = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        panelList = new javax.swing.JPanel();
        scrollKontak = new javax.swing.JScrollPane();
        listKontak = new javax.swing.JList<>();
        panelBawah = new javax.swing.JPanel();
        btnSort = new javax.swing.JButton();
        btnExportCSV = new javax.swing.JButton();
        btnHapusSemua = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.GridBagLayout());

        panelInput.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nama :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInput.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInput.add(txtNama, gridBagConstraints);

        jLabel2.setText("Alamat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInput.add(jLabel2, gridBagConstraints);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        txtAlamat.setPreferredSize(new java.awt.Dimension(240, 84));
        jScrollPane1.setViewportView(txtAlamat);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInput.add(jScrollPane1, gridBagConstraints);

        jLabel3.setText("Telepon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInput.add(jLabel3, gridBagConstraints);

        txtTelepon.setPreferredSize(new java.awt.Dimension(240, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelInput.add(txtTelepon, gridBagConstraints);

        mainPanel.add(panelInput, new java.awt.GridBagConstraints());

        panelTombol.setLayout(new java.awt.GridLayout(1, 4, 5, 5));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        panelTombol.add(btnTambah);

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        panelTombol.add(btnUbah);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        panelTombol.add(btnHapus);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        panelTombol.add(btnClear);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(53, 0, 0, 0);
        mainPanel.add(panelTombol, gridBagConstraints);

        panelCari.setLayout(new java.awt.GridLayout(1, 3, 5, 5));

        txtCari.setPreferredSize(new java.awt.Dimension(200, 22));
        panelCari.add(txtCari);

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        panelCari.add(btnCari);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        panelCari.add(btnReset);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = -384;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(53, 0, 0, 0);
        mainPanel.add(panelCari, gridBagConstraints);

        listKontak.setModel(new DefaultListModel());
        scrollKontak.setViewportView(listKontak);

        javax.swing.GroupLayout panelListLayout = new javax.swing.GroupLayout(panelList);
        panelList.setLayout(panelListLayout);
        panelListLayout.setHorizontalGroup(
            panelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollKontak, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        panelListLayout.setVerticalGroup(
            panelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(scrollKontak, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        mainPanel.add(panelList, gridBagConstraints);

        panelBawah.setLayout(new java.awt.GridLayout(1, 4, 5, 5));

        btnSort.setText("Sort A-Z");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });
        panelBawah.add(btnSort);

        btnExportCSV.setText("Export ke CSV");
        btnExportCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportCSVActionPerformed(evt);
            }
        });
        panelBawah.add(btnExportCSV);

        btnHapusSemua.setText("Hapus Semua");
        btnHapusSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusSemuaActionPerformed(evt);
            }
        });
        panelBawah.add(btnHapusSemua);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        panelBawah.add(btnKeluar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(53, 0, 0, 0);
        mainPanel.add(panelBawah, gridBagConstraints);
        mainPanel.add(jTabbedPane1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Event tombol Tambah:
     * - Validasi input
     * - Validasi nomor telepon
     * - Menambahkan data baru ke list
     */
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String nama = txtNama.getText();
        String alamat = txtAlamat.getText();
        String telepon = txtTelepon.getText();
        
        // Validasi input kosong
        if (nama.isEmpty() || alamat.isEmpty() || telepon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
            return;
        }
         // Validasi nomor telepon
        if (!isValidPhone(telepon)) {
            JOptionPane.showMessageDialog(this, "Nomor telepon tidak valid!");
            return;
        }
         // Menambah data ke model
        model.addElement(nama + " | " + alamat + " | " + telepon);
        clearInput(); // Bersihkan input
    }//GEN-LAST:event_btnTambahActionPerformed
    
    /**
     * Event tombol Ubah:
     * - Mengubah data pada indeks yang dipilih
     */
    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        int i = listKontak.getSelectedIndex();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Pilih kontak yang akan diubah!");
            return;
        }
        
        // Membuat data baru berdasarkan input terbaru
        String baru = txtNama.getText() + " | " + txtAlamat.getText() + " | " + txtTelepon.getText();
        
        model.set(i, baru); // Ubah data di indeks i

        clearInput();
    }//GEN-LAST:event_btnUbahActionPerformed
    
    /**
     * Event tombol Hapus:
     * Menghapus data kontak yang dipilih user.
     */
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int i = listKontak.getSelectedIndex();
        if (i != -1)
            model.remove(i);
    }//GEN-LAST:event_btnHapusActionPerformed
    
    /**
     * Tombol Clear:
     * Menghapus input tanpa mengubah list data.
     */
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearInput();
    }//GEN-LAST:event_btnClearActionPerformed
    
    /**
     * Tombol Cari:
     * Menampilkan hanya item yang mengandung keyword pencarian.
     */
    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String keyword = txtCari.getText().toLowerCase();

        DefaultListModel<String> filtered = new DefaultListModel<>();
        
        // Filter data berdasarkan keyword
        for (int i = 0; i < model.size(); i++) {
            if (model.get(i).toLowerCase().contains(keyword)) {
                filtered.addElement(model.get(i));
            }
        }

        listKontak.setModel(filtered);
    }//GEN-LAST:event_btnCariActionPerformed
    
    /**
     * Tombol Reset:
     * Mengembalikan tampilan list ke data asli.
     */
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        listKontak.setModel(model);
    }//GEN-LAST:event_btnResetActionPerformed
    
    /**
     * Tombol Sort:
     * Mengurutkan data A-Z berdasarkan nama.
     */
    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        ArrayList<String> data = new ArrayList<>();
        
        // Pindahkan data model ke ArrayList
        for (int i = 0; i < model.size(); i++) data.add(model.get(i));
        
        // Sort A-Z
        Collections.sort(data);
        model.clear();
        
        // Kembalikan ke model
        for (String s : data) model.addElement(s);
    }//GEN-LAST:event_btnSortActionPerformed

    /**
     * Tombol Export CSV:
     * Menyimpan semua data kontak ke file CSV.
     */
    private void btnExportCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportCSVActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {

                File f = chooser.getSelectedFile();
                FileWriter writer = new FileWriter(f);

                // Header CSV
                writer.write("Nama,Alamat,Telepon\n");

                // Tulis seluruh data
                for (int i = 0; i < model.size(); i++) {
                    String[] data = model.get(i).split("\\|");
                    writer.write(data[0].trim() + "," + data[1].trim() + "," + data[2].trim() + "\n");
                }

                writer.close();
                JOptionPane.showMessageDialog(this, "Berhasil Export CSV!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Export: " + e.getMessage());
        }
    }//GEN-LAST:event_btnExportCSVActionPerformed

    /**
     * Tombol Hapus Semua:
     * Menghapus seluruh data setelah konfirmasi.
     */
    private void btnHapusSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusSemuaActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Hapus semua?", "Konfirmasi", JOptionPane.YES_NO_OPTION)
            == JOptionPane.YES_OPTION)
            model.clear();
    }//GEN-LAST:event_btnHapusSemuaActionPerformed

    /**
     * Tombol Keluar:
     * Menutup aplikasi setelah konfirmasi user.
     */
    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin keluar?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aplikasiBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aplikasiBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aplikasiBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aplikasiBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aplikasiBukuAlamat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExportCSV;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapusSemua;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSort;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listKontak;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelBawah;
    private javax.swing.JPanel panelCari;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelList;
    private javax.swing.JPanel panelTombol;
    private javax.swing.JScrollPane scrollKontak;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}
